### ISSUE TITLE
Win state never reached.

### ISSUE THREAD

**Issue by Liamdoult** [ThePrimeagen/vim-be-good#5]
When playing the game I am unable to reach win state in any of the game modes (including my own). 

Running:
`:VimBeGood2 relative`

I get the game count down:
```
  1 Game is starting in 2 ...
~
~
~
```

Followed by the game state:
```
  1 Game Started:  1 / 10
  2 When you see a "DELETE ME", relative jump to it
  3 as fast as possible and delete it.
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
 23
 24
 25
 26                               DELETE ME
```

If I complete the task and by jumping to line 26 and deleting the contents of the line:
```
  1 Game Started:  1 / 10
  2 When you see a "DELETE ME", relative jump to it
  3 as fast as possible and delete it.
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
 23
 24
 25
 26
```
The game does not register that I have completed the task. This applies to `ci{` and my own game that I created.

My `:checkhealth` for reference:
```
  2 health#nvim#check
  3 ========================================================================
  4 ## Configuration
  5   - OK: no issues found
  6
  7 ## Performance
  8   - OK: Build type: RelWithDebInfo
  9
 10 ## Remote Plugins
 11   - OK: Up to date
 12
 13 ## terminal
 14   - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
 15   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
 16   - INFO: $XTERM_VERSION=''
 17   - INFO: $VTE_VERSION=''
 18   - INFO: $TERM_PROGRAM=''
 19   - INFO: $COLORTERM=''
 20   - INFO: $SSH_TTY=''
 21
 22 ## tmux
 23   - OK: escape-time: 0ms
 24   - INFO: $TERM: screen-256color
 25
 26 health#provider#check
 27 ========================================================================
 28 ## Clipboard (optional)
 29   - OK: Clipboard tool found: tmux
 30
 31 ## Python 2 provider (optional)
 32   - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
 33   - INFO: Executable: /usr/bin/python2
 34   - INFO: Python2 version: 2.7.15
 35   - INFO: python2-neovim version: 0.2.0 (outdated; from /usr/lib/python2.7/dist-packages/neovim)
 36   - WARNING: Latest python2-neovim is NOT installed: 0.3.1
 37
 38 ## Python 3 provider (optional)
 39   - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
 40   - INFO: Executable: /usr/bin/python3
 41   - INFO: Python3 version: 3.6.8
 42   - INFO: python3-neovim version: 0.2.0 (outdated; from /usr/lib/python3/dist-packages/neovim)
 43   - WARNING: Latest python3-neovim is NOT installed: 0.3.1
 44
 45 ## Ruby provider (optional)
 46   - WARNING: `ruby` and `gem` must be in $PATH.
 47     - ADVICE:
 48       - Install Ruby and verify that `ruby` and `gem` commands work.
 49
 50 ## Node provider (optional)
 51   - INFO: Node: v12.16.2
 52   - INFO: Host: /usr/local/bin/neovim-node-host
 53   - OK: Latest "neovim" npm is installed: 4.8.0
 54
```

After debugging, it appears that the `lines` event does not get invoked on changes to the game state. I confirmed this by adding printouts when `checkForWin` is called and it was never called. I added a call to checkForWin outside the event and the printout worked.

I attempted to look into the events provided by neovim and if they changed over different versions, but there seems to be very little information regarding the actual events that are available (Perhaps they are shared as part of the original vim documentation, however, I have not looked into that yet). 

I am not sure where to look into the events provided by Neovim and if that would be the actual cause of the issue?

Perhaps someone else has insight into this issue?

**Comment by brandoncc** [comment]
The `lines` event was one of the most difficult things about learning to work on this project. 

I had a lot of trouble getting printouts to work myself. I ended up debugging by running nvim like this: `NVIM_NODE_LOG_FILE=nvim.log nvim` and then using `console.log` which will show up in that log file. Can you try that and put log statements in `onLineEvent`, then check if they show up in the log file?

I would place `console.log('in line event handler ' + JSON.stringify(args))` as the first line of `onLineEvent`.

I also noticed that the round number is showing up for you, but it doesn't for me. That is interesting!

Let me know how it goes.

**Comment by Liamdoult** [comment]
Thanks for getting back to me. The log file was exactly what I was looking for!

I attached the log to `listenLines`:
``` javascript
this.listenLines = (args: any[]) => {
    console.log('in line event handler ' + JSON.stringify(args))
    if (this.linesCallback) {
        this.linesCallback(args);
    }
}
```

Full log output:
```
{"message":"host.start","level":"debug"}
{"level":"info","message":"handleRequest: "}
{"level":"debug","message":"request received: "}
{"level":"info","message":"handleRequest: "}
{"level":"debug","message":"request received: "}
{"message":"requested specs for /home/liam/.vim/bundle/vim-be-good/rplugin/node/vim-be-good","level":"debug"}
{"message":"createPlugin./home/liam/.vim/bundle/vim-be-good/rplugin/node/vim-be-good.clearCache: true","level":"debug"}
{"level":"debug","message":"getPlugin.alwaysInit"}
{"message":"[{\"type\":\"command\",\"name\":\"VimBeGood2\",\"sync\":false,\"opts\":{\"nargs\":\"*\"}}]","level":"debug"}
{"message":"specs: [\n  {\n    type: 'command',\n    name: 'VimBeGood2',\n    sync: false,\n    opts: { nargs: '*' }\n  }\n]","level":"debug"}
{"message":"host.start","level":"debug"}
{"level":"info","message":"handleRequest: "}
{"level":"debug","message":"request received: "}
{"level":"info","message":"handleRequest: "}
{"level":"debug","message":"request received: "}
{"message":"requested specs for /home/liam/.vim/bundle/vim-be-good/rplugin/node/vim-be-good","level":"debug"}
{"message":"createPlugin./home/liam/.vim/bundle/vim-be-good/rplugin/node/vim-be-good.clearCache: true","level":"debug"}
{"level":"debug","message":"getPlugin.alwaysInit"}
{"message":"[{\"type\":\"command\",\"name\":\"VimBeGood2\",\"sync\":false,\"opts\":{\"nargs\":\"*\"}}]","level":"debug"}
{"message":"specs: [\n  {\n    type: 'command',\n    name: 'VimBeGood2',\n    sync: false,\n    opts: { nargs: '*' }\n  }\n]","level":"debug"}
{"message":"host.start","level":"debug"}
{"level":"info","message":"handleRequest: "}
{"level":"debug","message":"request received: "}
{"level":"info","message":"handleRequest: "}
{"level":"debug","message":"request received: "}
{"message":"requested specs for /home/liam/.vim/bundle/vim-be-good/rplugin/node/vim-be-good","level":"debug"}
{"message":"createPlugin./home/liam/.vim/bundle/vim-be-good/rplugin/node/vim-be-good.clearCache: true","level":"debug"}
{"level":"debug","message":"getPlugin.alwaysInit"}
{"message":"[{\"type\":\"command\",\"name\":\"VimBeGood2\",\"sync\":false,\"opts\":{\"nargs\":\"*\"}}]","level":"debug"}
{"message":"specs: [\n  {\n    type: 'command',\n    name: 'VimBeGood2',\n    sync: false,\n    opts: { nargs: '*' }\n  }\n]","level":"debug"}
{"message":"host.start","level":"debug"}
{"level":"info","message":"handleRequest: "}
{"level":"debug","message":"request received: "}
{"level":"info","message":"handleNotification: "}
{"level":"debug","message":"host.handlePlugin: "}
{"message":"createPlugin./mnt/c/Users/Liam/Documents/projects/vim-be-good-bug-fix/rplugin/node/vim-be-good.clearCache: true","level":"debug"}
{"level":"debug","message":"getPlugin.alwaysInit"}
{"message":"request -> neovim.api.nvim_get_current_buf","level":"debug"}
{"message":"response -> neovim.api.nvim_get_current_buf: [object Object]","level":"debug"}
{"message":"request -> neovim.api.nvim_buf_line_count","level":"debug"}
{"message":"response -> neovim.api.nvim_buf_line_count: 1","level":"debug"}
{"message":"request -> neovim.api.nvim_buf_get_lines","level":"debug"}
{"message":"response -> neovim.api.nvim_buf_get_lines: ","level":"debug"}
{"message":"request -> neovim.api.nvim_get_current_buf","level":"debug"}
{"message":"response -> neovim.api.nvim_get_current_buf: [object Object]","level":"debug"}
{"message":"request -> neovim.api.nvim_get_current_win","level":"debug"}
{"message":"response -> neovim.api.nvim_get_current_win: [object Object]","level":"debug"}
{"message":"[vim-be-good] Game init","level":"info"}
{"message":"request -> neovim.api.nvim_buf_attach","level":"debug"}
{"message":"request -> neovim.api.nvim_buf_set_lines","level":"debug"}
{"message":"response -> neovim.api.nvim_buf_attach: null","level":"debug"}
{"level":"error","message":"Error making request to nvim_buf_attachnvim_buf_attach: Invalid method name","stack":"Error: Error making request to nvim_buf_attach\n    at Buffer.request (/usr/local/lib/node_modules/neovim/lib/api/Base.js:75:23)\n    at Buffer.<anonymous> (/usr/local/lib/node_modules/neovim/lib/api/Buffer.js:31:25)\n    at Generator.next (<anonymous>)\n    at /usr/local/lib/node_modules/neovim/lib/api/Buffer.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/local/lib/node_modules/neovim/lib/api/Buffer.js:4:12)\n    at Buffer.<computed> (/usr/local/lib/node_modules/neovim/lib/api/Buffer.js:28:58)\n    at Buffer.listen (/usr/local/lib/node_modules/neovim/lib/api/Buffer.js:298:33)\n    at new BaseGame (/mnt/c/Users/Liam/Documents/projects/vim-be-good-bug-fix/rplugin/node/vim-be-good/game/base.js:103:27)\n    at new DeleteGame (/mnt/c/Users/Liam/Documents/projects/vim-be-good-bug-fix/rplugin/node/vim-be-good/game/delete.js:16:9)"}
{"level":"info","message":"Unhandled Rejection at:"}
{"message":"response -> neovim.api.nvim_buf_set_lines: null","level":"debug"}
{"message":"request -> neovim.api.nvim_buf_set_lines","level":"debug"}
{"message":"response -> neovim.api.nvim_buf_set_lines: null","level":"debug"}
{"message":"request -> neovim.api.nvim_buf_set_lines","level":"debug"}
{"message":"response -> neovim.api.nvim_buf_set_lines: null","level":"debug"}
{"message":"request -> neovim.api.nvim_buf_set_lines","level":"debug"}
{"message":"response -> neovim.api.nvim_buf_set_lines: null","level":"debug"}
{"message":"request -> neovim.api.nvim_buf_line_count","level":"debug"}
{"message":"response -> neovim.api.nvim_buf_line_count: 1","level":"debug"}
{"message":"request -> neovim.api.nvim_buf_set_lines","level":"debug"}
{"message":"response -> neovim.api.nvim_buf_set_lines: null","level":"debug"}
{"message":"request -> neovim.api.nvim_buf_set_lines","level":"debug"}
{"message":"response -> neovim.api.nvim_buf_set_lines: null","level":"debug"}
{"message":"request -> neovim.api.nvim_command","level":"debug"}
{"message":"response -> neovim.api.nvim_command: null","level":"debug"}
{"message":"request -> neovim.api.nvim_buf_line_count","level":"debug"}
{"message":"response -> neovim.api.nvim_buf_line_count: 25","level":"debug"}
{"message":"request -> neovim.api.nvim_buf_set_lines","level":"debug"}
{"message":"response -> neovim.api.nvim_buf_set_lines: null","level":"debug"}
{"message":"request -> neovim.api.nvim_buf_set_lines","level":"debug"}
{"message":"response -> neovim.api.nvim_buf_set_lines: null","level":"debug"}
```

I also added a log in the game constructor just make sure that logs were being outputted correctly:
```
{"message":"[vim-be-good] Game init","level":"info"}
```

I played the game until the point where the game gets stuck. The log does not show the desired output but does raise the following error:
```
{"level":"error","message":"Error making request to nvim_buf_attachnvim_buf_attach: Invalid method name","stack":"Error: Error making request to nvim_buf_attach\n    at Buffer.request (/usr/local/lib/node_modules/neovim/lib/api/Base.js:75:23)\n    at Buffer.<anonymous> (/usr/local/lib/node_modules/neovim/lib/api/Buffer.js:31:25)\n    at Generator.next (<anonymous>)\n    at /usr/local/lib/node_modules/neovim/lib/api/Buffer.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/local/lib/node_modules/neovim/lib/api/Buffer.js:4:12)\n    at Buffer.<computed> (/usr/local/lib/node_modules/neovim/lib/api/Buffer.js:28:58)\n    at Buffer.listen (/usr/local/lib/node_modules/neovim/lib/api/Buffer.js:298:33)\n    at new BaseGame (/mnt/c/Users/Liam/Documents/projects/vim-be-good-bug-fix/rplugin/node/vim-be-good/game/base.js:103:27)\n    at new DeleteGame (/mnt/c/Users/Liam/Documents/projects/vim-be-good-bug-fix/rplugin/node/vim-be-good/game/delete.js:16:9)"}
{"level":"info","message":"Unhandled Rejection at:"}
```

I had a *very* quick look into this error and found that it could be related to my version of neovim:
```
:version
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-_mzR4z/neovim-0.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconve
rsion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -
Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-_mzR4z/neovim-0.2.2/build/config -I/build/neovim-_mzR4z/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/in
clude -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-_mzR4z/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-_mzR4z/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

It seems `v0.2.2` is very far behind the latest release. I will update my version and try again later and get back to you.

**Comment by brandoncc** [comment]
No problem, I'm happy to help. If that resolves it, we will have some good
info for the readme!

**Comment by ThePrimeagen** [comment]
@Liamdoult did brandoncc's fix ever work?

**Comment by Liamdoult** [comment]
Apologies for not following up. 

@ThePrimeagen I am not sure...

I updated my neovim version (`v0.2.2` -> `v0.4.3`). But before the `lines` listener is invoked, the game freezes. From what I can tell this is caused by the `this.state.buffer.setLines` never actually changing the state of the lines. The `await` is resolved but the content displayed on my screen never changes. 

I am not sure why I am having so many issues (perhaps its a calling from ubuntu/i3 to my inferior windows/WSL setup), and have not had any time look into it, unfortunately.

I am happy to collect any information you think would be relevant to the conversation. However, I am not sure this is an issue caused by this project, and rather some interface issues with neovim (and my setup)... I personally would not have a problem with closing this issue, until we know that other people are experiencing the same issue.

It will just be a shame that I do not get to wack any moles or jump any lines. But life goes on... 😂

**Comment by ThePrimeagen** [comment]
No, please keep the issue open.

Tonight I am going to be doing some "refuctoring" on this project and I hope to get it into a better state.  I'll be adding a lot of additional logging such that when these types of issues arise I can better debug it

**Comment by Liamdoult** [comment]
@ThePrimeagen 
Can confirm,
![image](https://user-images.githubusercontent.com/12427907/85543968-76fa4080-b612-11ea-8639-684415960d9e.png)
It works!

**Comment by ThePrimeagen** [comment]
awesome @Liamdoult !!
